# -*- coding: utf-8 -*-
"""Breast cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8fbPqAzhq7SzXQE1R4w7VIjR0TFzuc_

Data read
---
"""

import pandas as pd
df=pd.read_csv("/content/data.csv")
df.head()

"""#EDA"""

# removing the unnamed column
df.drop('Unnamed: 32',axis=1,inplace=True)

# remove the id column
df.drop("id",axis=1,inplace=True)

df.head()

# How many datpoins and featues
df.shape

# check the datatype of each column
df.info()

"""diagnosis column is a categorical column where remains are continous values"""

# checking missing values
df.isna().sum()

"""Statistical summary of the data - Descriptive statistical"""

df.describe()

"""checking the distrubution of target column"""

df['diagnosis'].value_counts()

"""Encode the target column diagnosis                """

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
labels=le.fit_transform(df["diagnosis"])
df['target'] = labels
df['target']

df.drop(columns='diagnosis',axis=1,inplace=True)

df.head()

"""There is an slight imbalance in target.But its fine in this case

grouping the data based on  the targets
"""

df.groupby('target').mean()

"""Data visualization"""

# for checking the taget cloumn is balanced or imbalanced
import seaborn as sns
sns.set()
sns.countplot(x='target',data=df)

# for getting all the column name
for i in df:
  print(i)

for i in df:
  sns.displot(x=i, data=df)

"""Finding Outlines in thhe dataset"""

import matplotlib.pyplot as plt
for column in df:
  plt.figure()
  df.boxplot([column])

"""Construct heatmap to visulizise the corelatio matrix"""

co_relation_matrix=df.corr()
plt.figure(figsize=(30,30))
sns.heatmap(co_relation_matrix,cbar=True, annot=True, cmap="Blues")
plt.savefig("corelation heat man")